package com.sumino.xyz.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF2196F3)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF3CA3FF)
val onPrimaryContainerLight = Color(0xFF001226)
val secondaryLight = Color(0xFF416084)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFBEDAFF)
val onSecondaryContainerLight = Color(0xFF224365)
val tertiaryLight = Color(0xFF873EA4)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFCD7FEA)
val onTertiaryContainerLight = Color(0xFF210030)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF8F9FF)
val onBackgroundLight = Color(0xFF181C22)
val surfaceLight = Color(0xFFF8F9FF)
val onSurfaceLight = Color(0xFF181C22)
val surfaceVariantLight = Color(0xFFDBE3F0)
val onSurfaceVariantLight = Color(0xFF404752)
val outlineLight = Color(0xFF707883)
val outlineVariantLight = Color(0xFFBFC7D4)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D3137)
val inverseOnSurfaceLight = Color(0xFFEEF1F9)
val inversePrimaryLight = Color(0xFF9ECAFF)
val surfaceDimLight = Color(0xFFD7DAE2)
val surfaceBrightLight = Color(0xFFF8F9FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF1F3FC)
val surfaceContainerLight = Color(0xFFEBEEF6)
val surfaceContainerHighLight = Color(0xFFE5E8F0)
val surfaceContainerHighestLight = Color(0xFFDFE2EA)



val primaryDark = Color(0xFFE5C36C)
val onPrimaryDark = Color(0xFF3E2E00)
val primaryContainerDark = Color(0xFF594400)
val onPrimaryContainerDark = Color(0xFFFFDF92)
val secondaryDark = Color(0xFFD6C5A0)
val onSecondaryDark = Color(0xFF392F15)
val secondaryContainerDark = Color(0xFF51462A)
val onSecondaryContainerDark = Color(0xFFF3E1BB)
val tertiaryDark = Color(0xFFAECFAC)
val onTertiaryDark = Color(0xFF1A361E)
val tertiaryContainerDark = Color(0xFF314D33)
val onTertiaryContainerDark = Color(0xFFC9EBC7)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF16130B)
val onBackgroundDark = Color(0xFFEAE1D4)
val surfaceDark = Color(0xFF16130B)
val onSurfaceDark = Color(0xFFEAE1D4)
val surfaceVariantDark = Color(0xFF4C4639)
val onSurfaceVariantDark = Color(0xFFCFC5B4)
val outlineDark = Color(0xFF989080)
val outlineVariantDark = Color(0xFF4C4639)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFEAE1D4)
val inverseOnSurfaceDark = Color(0xFF343027)
val inversePrimaryDark = Color(0xFF745B0B)
val surfaceDimDark = Color(0xFF16130B)
val surfaceBrightDark = Color(0xFF3D392F)
val surfaceContainerLowestDark = Color(0xFF110E07)
val surfaceContainerLowDark = Color(0xFF1F1B13)
val surfaceContainerDark = Color(0xFF231F17)
val surfaceContainerHighDark = Color(0xFF2E2A21)
val surfaceContainerHighestDark = Color(0xFF39342B)
